apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghanawaters-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Will be patched in overlays