apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghanawaters-prod
resources:
  - ../../base/admin
  - ../../base/api
  - ../../base/frontend
  - ../../base/database
  - ../../base/jobs
  - ../../base/nanomq
  - configs/api-config.yaml
images:
  - name: ghananauticalinfo/ghanawaters-admin
    newTag: IMAGE_TAG
  - name: ghananauticalinfo/ghanawaters-api
    newTag: IMAGE_TAG
  - name: ghananauticalinfo/ghanawaters-frontend
    newTag: IMAGE_TAG
patches:
  - path: patches/ingress-hosts.yaml
  - path: patches/replicas.yaml
  - path: patches/database-resources.yaml
  - path: patches/migration-command.yaml
  - path: patches/api-configmap.yaml
  - path: patches/nanomq-ingress-host.yaml
    target:
      kind: Ingress
      name: ghanawaters-nanomq-ingress
  - path: patches/nanomq-config.yaml
    target:
      kind: ConfigMap
      name: ghanawaters-nanomq-config
  - path: patches/nanomq-resources.yaml
    target:
      kind: Deployment
      name: ghanawaters-nanomq
