apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghanawaters-frontend
  namespace: ghanawaters-test
  labels:
    app: ghanawaters-frontend
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghanawaters-frontend
      env: test
  template:
    metadata:
      labels:
        app: ghanawaters-frontend
        env: test
    spec:
      containers:
      - name: ghanawaters-frontend
        image: ghananauticalinfo/ghanawaters-frontend:test-develop
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ghanawaters-frontend-service
  namespace: ghanawaters-test
spec:
  selector:
    app: ghanawaters-frontend
    env: test
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghanawaters-frontend-ingress
  namespace: ghanawaters-test
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ghanawaters-test.ghananautical.info
    secretName: test-ghanawaters-tls
  rules:
  - host: ghanawaters-test.ghananautical.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ghanawaters-frontend-service
            port:
              number: 80