// Auto-generated by setup-keycloak-local.sh
// DO NOT EDIT - will be overwritten
export const environment = {
  production: false,
  apiUrl: '/api',
  frontendUrl: 'http://localhost:4200',
  buildTag: 'development',
  keycloak: {
    url: 'http://localhost:8080',
    realm: 'ghanawaters',
    clientId: 'ghanawaters-admin'
  }
};
