apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghanawaters-api
spec:
  template:
    spec:
      containers:
      - name: ghanawaters-api
        envFrom:
        - configMapRef:
            name: ghanawaters-api-config