apiVersion: batch/v1
kind: Job
metadata:
  name: ghanawaters-api-migrations
spec:
  template:
    spec:
      containers:
      - name: migrations
        args:
          - |
            cd /app
            echo "Running DEV migrations for ${NODE_ENV} environment..."
            npm run migration:run