apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghanawaters-dev

resources:
- ../../base/admin
- ../../base/api
- ../../base/frontend
- ../../base/database
- ../../base/jobs

images:
- name: ghananauticalinfo/ghanawaters-admin
  newName: ghananauticalinfo/ghanawaters-admin
  newTag: dev-develop-56d8db6d42e96797470ac124301c565c435b4e8e
- name: ghananauticalinfo/ghanawaters-api
  newName: ghananauticalinfo/ghanawaters-api
  newTag: dev-develop-56d8db6d42e96797470ac124301c565c435b4e8e
- name: ghananauticalinfo/ghanawaters-frontend
  newName: ghananauticalinfo/ghanawaters-frontend
  newTag: dev-develop-56d8db6d42e96797470ac124301c565c435b4e8e

patches:
- path: patches/ingress-hosts.yaml
- path: patches/replicas.yaml
- path: patches/database-resources.yaml
- path: patches/node-env.yaml
- path: patches/migration-command.yaml
