apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghanawaters-dev

resources:
- ../../base/admin
- ../../base/api
- ../../base/frontend
- ../../base/database
- ../../base/jobs
- configs/api-config.yaml

images:
- name: ghananauticalinfo/ghanawaters-admin
  newName: ghananauticalinfo/ghanawaters-admin
  newTag: dev-develop-c6418ac17128b169d795e2fff688319069ea60c4
- name: ghananauticalinfo/ghanawaters-api
  newName: ghananauticalinfo/ghanawaters-api
  newTag: dev-develop-c6418ac17128b169d795e2fff688319069ea60c4
- name: ghananauticalinfo/ghanawaters-frontend
  newName: ghananauticalinfo/ghanawaters-frontend
  newTag: dev-develop-c6418ac17128b169d795e2fff688319069ea60c4

patches:
- path: patches/ingress-hosts.yaml
- path: patches/replicas.yaml
- path: patches/database-resources.yaml
- path: patches/node-env.yaml
- path: patches/migration-command.yaml
- path: patches/api-configmap.yaml
