apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/admin
  - ../../base/api
  - ../../base/frontend
  - ../../base/database

images:
  - name: ghananauticalinfo/ghanawaters-admin
    newTag: dev-latest
  - name: ghananauticalinfo/ghanawaters-api
    newTag: dev-latest
  - name: ghananauticalinfo/ghanawaters-frontend
    newTag: dev-latest

patches:
  - path: patches/ingress-hosts.yaml
  - path: patches/replicas.yaml
  - path: patches/database-resources.yaml
  - path: patches/node-env.yaml