# File: .github/workflows/deploy-snapper-frontend-prod.yml
name: Deploy Snapper Frontend to Production

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/frontend/**'
      - 'libs/**'  # Include changes to shared libraries
      - 'package.json'
      - 'package-lock.json'
      - 'nx.json'
      - '.github/workflows/deploy-snapper-frontend-prod.yml'
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Type "deploy-to-production" to confirm'
        required: true

jobs:
  check-confirmation:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    outputs:
      confirmed: ${{ steps.confirm.outputs.confirmed }}
    steps:
      - id: confirm
        run: |
          if [ "${{ github.event.inputs.confirm_deployment }}" == "deploy-to-production" ]; then
            echo "confirmed=true" >> $GITHUB_OUTPUT
          else
            echo "confirmed=false" >> $GITHUB_OUTPUT
            echo "::error::Deployment not confirmed. Please type 'deploy-to-production' to confirm."
            exit 1
          fi

  deploy:
    needs: [check-confirmation]
    if: always() && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && needs.check-confirmation.outputs.confirmed == 'true'))
    uses: ./.github/workflows/nx-app-deploy.yml
    with:
      app_name: frontend
      environment: prod
      image_name: snapper-frontend
      domain_name: snapper.ghananautical.info
      compare_branch: main
    secrets: inherit